# 已验证的 meteoblue URL，其余为空待补充
# 格式: https://www.meteoblue.com/en/weather/week/{slug}_{id}
# 在 meteoblue.com 搜索 "{城市名} {ICAO码}"，点进机场页，复制 URL

METEO_URL_OVERRIDE = {
    "Amsterdam": "https://www.meteoblue.com/en/weather/week/amsterdam-airport-schiphol_the-netherlands_6296680",
    "Ankara": "",
    "Atlanta": "https://www.meteoblue.com/en/weather/week/hartsfield-jackson-atlanta-international-airport_united-states_4199556",
    "Austin": "",
    "Beijing": "https://www.meteoblue.com/en/weather/week/beijing-capital-international-airport_china_6301354",
    "Buenos Aires": "https://www.meteoblue.com/en/weather/week/buenos-aires_argentina_3435910",
    "Busan": "",
    "Cape Town": "",
    "Chengdu": "",
    "Chicago": "",
    "Chongqing": "",
    "Dallas": "https://www.meteoblue.com/en/weather/week/dallas-love-field_united-states_4684922",
    "Denver": "",
    "Guangzhou": "",
    "Helsinki": "",
    "Hong Kong": "",
    "Houston": "https://www.meteoblue.com/en/weather/week/houston-hobby_united-states_4741989",
    "Istanbul": "https://www.meteoblue.com/en/weather/week/istanbul-airport_republic-of-t%c3%bcrkiye_11838481",
    "Jeddah": "",
    "Karachi": "",
    "Kuala Lumpur": "",
    "London": "https://www.meteoblue.com/en/weather/week/london-city-airport_united-kingdom_6296599",
    "Los Angeles": "",
    "Lucknow": "",
    "Madrid": "",
    "Manila": "",
    "Mexico City": "",
    "Miami": "https://www.meteoblue.com/en/weather/week/miami-international-airport_united-states_4164181",
    "Milan": "",
    "Moscow": "",
    "Munich": "",
    "Nyc": "",  # 搜索 "New York KLGA" 或 "LaGuardia"
    "Panama City": "",
    "Paris": "",
    "Qingdao": "",
    "San Francisco": "",
    "Sao Paulo": "",
    "Seattle": "",
    "Seoul": "",
    "Shanghai": "",
    "Shenzhen": "",
    "Singapore": "https://www.meteoblue.com/en/weather/week/singapore-changi-airport_singapore_1880725",
    "Taipei": "",
    "Tel Aviv": "",
    "Tokyo": "https://www.meteoblue.com/en/weather/week/tokyo-international-airport_japan_6300412",
    "Toronto": "https://www.meteoblue.com/en/weather/week/toronto-pearson-international-airport_canada_6296338",
    "Warsaw": "",
    "Wellington": "",
    "Wuhan": "",
}
